### ISSUE TITLE
Errors parsing kml

### ISSUE THREAD

**Issue by orgicus** [araichev/kml2geojson#1]
I've tried to convert a kml file and got this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/kml2geojson", line 9, in <module>
    load_entry_point('kml2geojson==3.0.4', 'console_scripts', 'kml2geojson')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/kml2geojson/kml2geojson.py", line 598, in main
    root = md.parseString(kml_str)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 589038-589039: ordinal not in range(128)
```
Using the default python 2.7 installed on OSX (10.11.5)
Any hints on how I could get pas this error ?

(Additionally pathlib is a depdendency, without it I got an import error:
```
Traceback (most recent call last):
  File "/usr/local/bin/kml2geojson", line 9, in <module>
    load_entry_point('kml2geojson==3.0.4', 'console_scripts', 'kml2geojson')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/kml2geojson/kml2geojson.py", line 3, in <module>
    import pathlib
ImportError: No module named pathlib
``` , perhaps the readme can mention that ?)

**Comment by araichev** [comment]
Hello orgicus, kml2geojson is a Python 3.4+ package. Use it with Python 2.7 at your own risk. Sorry, i don't have an insight into your error. If you figure it out, though, and want to add Python 2.7 support to the package, you are welcome to send me a merge request.
