### ISSUE TITLE
Version 4.0.1 breaks the install

### ISSUE THREAD

**Issue by drmattyg** [araichev/kml2geojson#7]
Previously used version 4.0.0 and it worked great (thanks!).  Recently tried to install in a fresh Python 3.5 virtualenv and saw the following failure:
```
Collecting kml2geojson
  Downloading https://kairosaerospace.jfrog.io/kairosaerospace/api/pypi/kairos-pypi-python3/packages/a3/cc/fb95481e0f94e5db164241009df0ab8393292e69c9d81fcdfcc5b0fc9d3c/kml2geojson-4.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7l/vrs5k9ts0mbdc45fb7c1z5fw0000gn/T/pip-build-uj20awhk/kml2geojson/setup.py", line 7, in <module>
        with open('LICENSE') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7l/vrs5k9ts0mbdc45fb7c1z5fw0000gn/T/pip-build-uj20awhk/kml2geojson/
```

Setting the dependency to kml2geojson==4.0.0 fixed the issue.  This is on OSX.

**Comment by araichev** [comment]
Whoops, i forgot a line in ``setup.py``.
Should work now.
Thanks for your report, drmattyg.
